export {
  configureApiClient,
  configureClient,
  getApiBaseUrl,
  resetApiClientForTests,
  ApiConfigError,
} from './config';
export {
  claimSubmission,
  createStaffQuestion,
  createSubmission,
  deleteStaffQuestion,
  downloadAccessory,
  fetchAdminDevices,
  fetchAdminSubmissions,
  fetchLeaderboard,
  fetchQuestions,
  fetchStaffQuestions,
  fetchSubmission,
  resendDeviceCommand,
  SUBMISSION_SECRET_HEADER,
  updateStaffQuestion,
} from './client';
export { normalizeApiError, normalizeNetworkError } from './errors';
export {
  ACCESSORY_POLL_INTERVAL_MS,
  ACCESSORY_POLL_TIMEOUT_MS,
  questionKeys,
  questionsQueryOptions,
  resendCommandMutationOptions,
  staffQuestionsQueryOptions,
  submitAnswersMutationOptions,
  submissionKeys,
  submissionQueryOptions,
  adminDevicesQueryOptions,
  adminSubmissionsQueryOptions,
  createQuestionMutationOptions,
  deleteQuestionMutationOptions,
  leaderboardQueryOptions,
  updateQuestionMutationOptions,
} from './queries';
export {
  ApiClientError,
  type AccessoryStatus,
  type AnswerSubmission,
  type ApiErrorBody,
  type ClaimResponse,
  type CreateSubmissionRequest,
  type CreateSubmissionResponse,
  type LeaderboardEntry,
  type PageResponse,
  type Question,
  type ResendCommandResult,
  type ScoredAnswer,
  type StaffQuestion,
  type SubmissionDetail,
  type UpsertQuestion,
  type AdminDevice,
  type AdminSubmission,
} from './types';
